// Aim Enterprise — content renderer
// Client edits config.json only. Do not edit this file for content changes.

const SERVICE_ICONS = [
  `<svg viewBox="0 0 100 100" width="46" height="46"><rect x="18" y="18" width="46" height="46" transform="rotate(45 41 41)" fill="none" stroke="var(--navy-2)" stroke-width="6"/><rect x="46" y="46" width="34" height="34" fill="var(--cyan)"/></svg>`,
  `<svg viewBox="0 0 100 100" width="46" height="46"><path d="M18,82 L82,18" stroke="var(--white)" stroke-opacity="0.85" stroke-width="7" fill="none" stroke-linecap="square"/><path d="M42,18 L82,18 L82,58" stroke="var(--white)" stroke-opacity="0.85" stroke-width="7" fill="none" stroke-linecap="square" stroke-linejoin="miter"/></svg>`,
  `<svg viewBox="0 0 100 100" width="46" height="46"><rect x="12" y="20" width="76" height="46" fill="none" stroke="var(--cyan)" stroke-width="6"/><path d="M28,66 L28,86 L48,66 Z" fill="var(--cyan)"/></svg>`,
  `<svg viewBox="0 0 100 100" width="46" height="46"><rect x="12" y="12" width="76" height="76" fill="none" stroke="var(--navy)" stroke-width="6"/><path d="M40,30 L70,50 L40,70 Z" fill="var(--navy)"/></svg>`
];

function el(tag, className, html) {
  const e = document.createElement(tag);
  if (className) e.className = className;
  if (html !== undefined) e.innerHTML = html;
  return e;
}

function render(cfg) {
  // Meta
  document.getElementById('pageTitle').textContent = cfg.site.title;
  document.getElementById('pageDescription').setAttribute('content', cfg.site.description);

  // Logo (header + footer)
  document.getElementById('logoImg').src = cfg.logo.src;
  document.getElementById('logoImg').alt = cfg.logo.alt;
  document.getElementById('footerLogoImg').src = cfg.logo.src;
  document.getElementById('footerLogoImg').alt = cfg.logo.alt;

  // Header nav
  const navLinks = document.getElementById('navLinks');
  cfg.header.navLinks.forEach(link => {
    const li = el('li', null, `<a href="${link.href}">${link.label}</a>`);
    navLinks.appendChild(li);
  });
  const headerCta = document.getElementById('headerCta');
  headerCta.textContent = cfg.header.ctaLabel;
  headerCta.href = cfg.header.ctaHref;

  // Hero
  document.getElementById('heroEyebrow').textContent = cfg.hero.eyebrow;
  document.getElementById('heroHeading').innerHTML =
    `${cfg.hero.headingBeforeAccent}<span class="accent">${cfg.hero.headingAccent}</span>${cfg.hero.headingAfterAccent}`;
  document.getElementById('heroParagraph').textContent = cfg.hero.paragraph;
  const heroPrimary = document.getElementById('heroPrimaryCta');
  heroPrimary.textContent = cfg.hero.primaryCta.label;
  heroPrimary.href = cfg.hero.primaryCta.href;
  const heroSecondary = document.getElementById('heroSecondaryCta');
  heroSecondary.textContent = cfg.hero.secondaryCta.label;
  heroSecondary.href = cfg.hero.secondaryCta.href;

  // Marquee (duplicated once for seamless scroll, matching original)
  const marqueeTrack = document.getElementById('marqueeTrack');
  const marqueeHtml = cfg.marquee.map(word => `<span>${word}</span>`).join('');
  marqueeTrack.innerHTML = marqueeHtml + marqueeHtml;

  // Services
  document.getElementById('servicesHeading').textContent = cfg.services.heading;
  document.getElementById('servicesParagraph').textContent = cfg.services.paragraph;
  const servicesGrid = document.getElementById('servicesGrid');
  cfg.services.items.forEach((item, i) => {
    const card = el('div', 'service-card frame-corners', `
      <span class="service-tag">${item.tag}</span>
      <div class="service-icon">${SERVICE_ICONS[i % SERVICE_ICONS.length]}</div>
      <h3>${item.title}</h3>
      <p>${item.text}</p>
    `);
    servicesGrid.appendChild(card);
  });

  // Approach
  document.getElementById('approachHeading').textContent = cfg.approach.heading;
  document.getElementById('approachParagraph').textContent = cfg.approach.paragraph;
  const approachSteps = document.getElementById('approachSteps');
  cfg.approach.steps.forEach(step => {
    const div = el('div', 'step', `
      <span class="num">${step.num}</span>
      <h3>${step.title}</h3>
      <p>${step.text}</p>
    `);
    approachSteps.appendChild(div);
  });

  // Work
  document.getElementById('workHeading').textContent = cfg.work.heading;
  document.getElementById('workParagraph').textContent = cfg.work.paragraph;
  document.getElementById('workNote').textContent = cfg.work.note;
  const workGrid = document.getElementById('workGrid');
  cfg.work.tiles.forEach(tile => {
    const bg = tile.image && tile.image.trim() !== ''
      ? `background-image:url('${tile.image}');background-size:cover;background-position:center;`
      : `background:${tile.gradient};`;
    const div = el('div', 'work-tile', `
      <div class="tile-bg" style="${bg}"></div>
      <div class="tile-info"><span class="cat">${tile.category}</span><h4>${tile.title}</h4></div>
    `);
    workGrid.appendChild(div);
  });

  // Stats
  const statsGrid = document.getElementById('statsGrid');
  cfg.stats.forEach(stat => {
    const div = el('div', 'stat', `<span class="big">${stat.big}</span><span class="label">${stat.label}</span>`);
    statsGrid.appendChild(div);
  });

  // CTA band
  document.getElementById('ctaEyebrow').textContent = cfg.cta.eyebrow;
  document.getElementById('ctaHeading').textContent = cfg.cta.heading;
  const ctaEmailBtn = document.getElementById('ctaEmailBtn');
  ctaEmailBtn.textContent = cfg.cta.emailLabel;
  ctaEmailBtn.href = `mailto:${cfg.cta.email}`;
  const ctaCallBtn = document.getElementById('ctaCallBtn');
  ctaCallBtn.textContent = cfg.cta.callLabel;
  ctaCallBtn.href = `tel:${cfg.cta.phone}`;

  // Footer
  document.getElementById('footerTagline').textContent = cfg.footer.tagline;
  const companyLinks = document.getElementById('footerCompanyLinks');
  cfg.footer.company.forEach(link => {
    const a = el('a', null, link.label);
    a.href = link.href;
    companyLinks.appendChild(a);
  });
  const contactLinks = document.getElementById('footerContactLinks');
  contactLinks.innerHTML = `
    <a href="mailto:${cfg.footer.contact.email}">${cfg.footer.contact.email}</a>
    <a href="tel:${cfg.footer.contact.phone}">${cfg.footer.contact.phoneDisplay}</a>
  `;
  const socialLinks = document.getElementById('footerSocialLinks');
  cfg.footer.social.forEach(link => {
    const a = el('a', null, link.label);
    a.href = link.href;
    socialLinks.appendChild(a);
  });
  document.getElementById('footerCopyright').textContent = cfg.footer.copyright;
  document.getElementById('footerTagRight').textContent = cfg.footer.tagRight;
}

function initInteractions() {
  // header scroll state
  const header = document.getElementById('siteHeader');
  window.addEventListener('scroll', () => {
    header.classList.toggle('scrolled', window.scrollY > 40);
  });

  // scroll reveal
  const revealEls = document.querySelectorAll('.reveal');
  const io = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('in');
        io.unobserve(entry.target);
      }
    });
  }, { threshold: 0.15 });
  revealEls.forEach(elem => io.observe(elem));
}

try {
  render(SITE_CONFIG);
  initInteractions();
} catch (err) {
  console.error(err);
  document.body.insertAdjacentHTML('afterbegin',
    '<p style="color:#fff;background:#c0392b;padding:12px;text-align:center;">Could not load config.js — check the file is present and valid.</p>');
}
